package org.codegen.core.constant;

public enum MetadataSource {
  JPA_ENTITY,
  XML_FILE,
  JSON_FILE,
  YAML_FILE,
  CSV_FILE,
  EXCEL_FILE,
  H2_DATABASE,
  HIVE_DATABASE,
  MYSQL_DATABASE,
  ORACLE_DATABASE,
  POSTGRESQL_DATABASE,
  SQLSERVER_DATABASE,
  MONGODB_DATABASE,
  REDIS_DATABASE,
  ELASTICSEARCH_DATABASE,
}
