[database]
driver = "mysql"
dsn = "user:pass@tcp(localhost:3306)/mydb"

[generator]
lang = ["java", "typescript"]
output = "./generated"
templateDir = "./generator/templates"

[typeMapping]
"varchar" = "String"
"int" = "number"
"timestamp" = "Date"
